"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildScript = exports.getIOSParams = exports.getAndParams = exports.ParseConfig = void 0;
var parseConfig_1 = require("./parseConfig");
Object.defineProperty(exports, "ParseConfig", { enumerable: true, get: function () { return parseConfig_1.ParseConfig; } });
var buildParams_1 = require("./and/buildParams");
Object.defineProperty(exports, "getAndParams", { enumerable: true, get: function () { return buildParams_1.getAndParams; } });
var buildParams_2 = require("./ios/buildParams");
Object.defineProperty(exports, "getIOSParams", { enumerable: true, get: function () { return buildParams_2.getIOSParams; } });
var buildScript_1 = require("./buildScript");
Object.defineProperty(exports, "BuildScript", { enumerable: true, get: function () { return buildScript_1.BuildScript; } });
