"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BuildScript = exports.getIOSParams = exports.getAndParams = exports.ParseConfig = void 0;
var parseConfig_mjs_1 = require("./parseConfig.mjs");
Object.defineProperty(exports, "ParseConfig", { enumerable: true, get: function () { return parseConfig_mjs_1.ParseConfig; } });
var buildParams_mjs_1 = require("./and/buildParams.mjs");
Object.defineProperty(exports, "getAndParams", { enumerable: true, get: function () { return buildParams_mjs_1.getAndParams; } });
var buildParams_mjs_2 = require("./ios/buildParams.mjs");
Object.defineProperty(exports, "getIOSParams", { enumerable: true, get: function () { return buildParams_mjs_2.getIOSParams; } });
var buildScript_mjs_1 = require("./buildScript.mjs");
Object.defineProperty(exports, "BuildScript", { enumerable: true, get: function () { return buildScript_mjs_1.BuildScript; } });
